[[headers]]
  for = "/*"
  [headers.values]	
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
	X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "form-action https:"	
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
	Feature-Policy = vibrate=(), geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), payment=()